source "https://rubygems.org"

gem "bigdecimal"
gem "builder", "~> 3.0"
gem "middleman", "~> 4.2"
gem "middleman-autoprefixer", "~> 3.0"
gem "middleman-blog", "~> 4.0"
gem "middleman-gh_pages"
gem "middleman-syntax"
gem "mutex_m"
gem "redcarpet"
gem "webrick"
